/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_scanf.check" instead.
 */

#include <check.h>

#line 1 "s21_scanf.check"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sscanf.h"

START_TEST(sscanf_h) {
#line 9
  unsigned short hu1 = 0;
  ck_assert_int_eq(sscanf("12345", "%hu", &hu1),
                   s21_sscanf("12345", "%hu", &hu1));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, sscanf_h);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
